language: node_js

node_js:
  - '16.15.0'

cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master

install:
  - npm install

script:
  - npm run deploy
